apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loaddshi9085-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loaddshi9085-tenant-component
    app.kubernetes.io/part-of: loaddshi9085-tenant-app
  name: loaddshi9085-tenant-component
  namespace: loaddshi9085-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loaddshi9085-tenant-component
    weight: null
status: {}
