apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loaddshi9085-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loaddshi9085-tenant-component
    app.kubernetes.io/part-of: loaddshi9085-tenant-app
  name: loaddshi9085-tenant-component
  namespace: loaddshi9085-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loaddshi9085-tenant-component
status:
  loadBalancer: {}
